using System;
using System.IO;
using System.IO.Compression;
using System.Reflection;
using System.Text;
using CCSwitchUpdater;
[assembly: AssemblyVersion("9.8.7.0")]
[assembly: AssemblyFileVersion("9.8.7.0")]
[assembly: AssemblyProduct("CC Switch")]
class Tests {
 static int failed, passed; static string root, fixture;
 static void Assert(bool yes, string why) { if(!yes) throw new Exception(why); }
 static void Reject(Action work) { try { work(); } catch(InvalidDataException) { return; } throw new Exception("Expected InvalidDataException"); }
 static void Test(string name, Action work) { try { work(); passed++; Console.WriteLine("PASS " + name); } catch(Exception e) { failed++; Console.WriteLine("FAIL " + name + ": " + e.GetType().Name + " " + e.Message); } }
 static string Dir() { string p = Path.Combine(root, Guid.NewGuid().ToString("N")); Directory.CreateDirectory(p); return p; }
 static void Zip(string path, params string[] names) { using(var z = ZipFile.Open(path, ZipArchiveMode.Create)) { foreach(var name in names) { var e = z.CreateEntry(name); using(var s = e.Open()) { byte[] b = name.Equals("cc-switch.exe", StringComparison.OrdinalIgnoreCase) ? File.ReadAllBytes(Assembly.GetExecutingAssembly().Location) : Encoding.UTF8.GetBytes("portable=true\r\n"); s.Write(b,0,b.Length); } } } }
 static Release R() { return new Release { Version = new Version(9,8,7,0), Tag = "v9.8.7", Size = 3, Digest = "sha256:ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad" }; }
 static string Target(string d) { File.WriteAllText(Path.Combine(d,"cc-switch.exe"),"old"); File.WriteAllText(Path.Combine(d,"portable.ini"),"portable=true"); File.WriteAllText(Path.Combine(d,"Reasonix.exe"),"untouched"); return Path.Combine(d,"cc-switch.exe"); }
 static int Main(string[] args) {
  root = Path.Combine(Path.GetTempPath(), "ccswitch-helper-tests-" + Guid.NewGuid().ToString("N")); Directory.CreateDirectory(root); fixture = File.ReadAllText(args[0]);
  Test("numeric version 3.20 > 3.9; ignore folder and normalize fourth segment", delegate { Assert(Core.ParseVersion("v3.20.1") > Core.ParseVersion("3.9.9"),"numeric comparison"); Assert(Core.ParseVersion("3.20.1") == Core.ParseVersion("3.20.1.0"),"normalize"); });
  Test("reject prerelease and malformed versions", delegate { Reject(delegate { Core.ParseVersion("v3.20.1-rc.1"); }); Reject(delegate { Core.ParseVersion("3.20"); }); });
  Test("select x64 portable not ARM64 or MSI from official fixture", delegate { var r=Core.SelectRelease(fixture,"x64"); Assert(r.AssetName=="CC-Switch-v3.20.1-Windows-Portable.zip", "wrong asset"); Assert(r.Size==13607261,"size"); });
  Test("select ARM64 portable", delegate { Assert(Core.SelectRelease(fixture,"arm64").AssetName=="CC-Switch-v3.20.1-Windows-arm64-Portable.zip","wrong ARM asset"); });
  Test("reject prerelease release metadata", delegate { Reject(delegate { Core.SelectRelease(fixture.Replace("\"prerelease\": false", "\"prerelease\": true"),"x64"); }); });
  Test("reject unsupported architecture", delegate { Reject(delegate { Core.SelectRelease(fixture,"x86"); }); });
  Test("reject missing or untrusted digest", delegate { Reject(delegate { Core.SelectRelease(fixture.Replace("sha256:", "md5:"),"x64"); }); });
  Test("reject duplicate matching assets", delegate { int pos=fixture.IndexOf("\"assets\""); Assert(pos>=0,"fixture"); string extra=fixture.Replace("CC-Switch-v3.20.1-Windows-arm64-Portable.zip","CC-Switch-v3.20.1-Windows-Portable.zip"); Reject(delegate { Core.SelectRelease(extra,"x64"); }); });
  Test("restrict URLs to exact official HTTPS repository and hosts", delegate { Assert(Core.IsAllowedUrl("https://github.com/farion1231/cc-switch/releases/download/v3.20.1/a.zip",true),"official"); Assert(!Core.IsAllowedUrl("https://github.com.evil.test/farion1231/cc-switch/releases/download/a.zip",true),"spoof"); Assert(!Core.IsAllowedUrl("http://github.com/farion1231/cc-switch/releases/download/a.zip",true),"http"); Assert(!Core.IsAllowedUrl("https://github.com/other/cc-switch/releases/download/a.zip",true),"other owner"); Assert(!Core.IsAllowedUrl("https://user@github.com/farion1231/cc-switch/releases/download/a.zip",true),"userinfo"); });
  Test("verify SHA-256 known vector", delegate { string p=Path.Combine(Dir(),"a"); File.WriteAllText(p,"abc",new UTF8Encoding(false)); Core.VerifyPackage(p,R()); Assert(Core.Sha256(p)=="ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad","hash"); });
  Test("reject wrong size and hash", delegate { string p=Path.Combine(Dir(),"a"); File.WriteAllText(p,"abd",new UTF8Encoding(false)); Reject(delegate { Core.VerifyPackage(p,R()); }); File.WriteAllText(p,"abcd"); Reject(delegate { Core.VerifyPackage(p,R()); }); });
  Test("read PE architecture and executable version", delegate { string p=Assembly.GetExecutingAssembly().Location; Assert(Core.ReadArchitecture(p)=="x86","fixture PE"); Assert(Core.ReadVersion(p)==new Version(9,8,7,0),"version"); });
  Test("reject non-PE executable", delegate { string p=Path.Combine(Dir(),"cc-switch.exe"); File.WriteAllText(p,"not an executable"); Reject(delegate { Core.ReadArchitecture(p); }); });
  Test("extract supported portable layout", delegate { string d=Dir(), z=Path.Combine(d,"a.zip"); Zip(z,"cc-switch.exe","portable.ini"); string p=Core.ExtractPackage(z,Path.Combine(d,"stage"),R(),"x86"); Assert(File.Exists(p),"missing binary"); Assert(Core.ReadVersion(p)==new Version(9,8,7,0),"version"); });
  Test("reject path traversal before writing any member", delegate { string d=Dir(),z=Path.Combine(d,"a.zip"),stage=Path.Combine(d,"stage"); Zip(z,"cc-switch.exe","../outside.exe","portable.ini"); Reject(delegate { Core.ExtractPackage(z,stage,R(),"x86"); }); Assert(!File.Exists(Path.Combine(d,"outside.exe")),"escaped"); Assert(!File.Exists(Path.Combine(stage,"cc-switch.exe")),"partial extraction"); });
  Test("reject unrelated executable in release", delegate { string d=Dir(), z=Path.Combine(d,"a.zip"); Zip(z,"cc-switch.exe","portable.ini","Reasonix.exe"); Reject(delegate { Core.ExtractPackage(z,Path.Combine(d,"stage"),R(),"x86"); }); });
  Test("reject case-insensitive duplicate executable", delegate { string d=Dir(),z=Path.Combine(d,"a.zip"); Zip(z,"cc-switch.exe","CC-SWITCH.EXE","portable.ini"); Reject(delegate { Core.ExtractPackage(z,Path.Combine(d,"stage"),R(),"x86"); }); });
  Test("reject missing portable marker", delegate { string d=Dir(),z=Path.Combine(d,"a.zip"); Zip(z,"cc-switch.exe"); Reject(delegate { Core.ExtractPackage(z,Path.Combine(d,"stage"),R(),"x86"); }); });
  Test("reject package version mismatch", delegate { string d=Dir(),z=Path.Combine(d,"a.zip"); Zip(z,"cc-switch.exe","portable.ini"); Release r=R(); r.Version=new Version(3,20,1,0); Reject(delegate { Core.ExtractPackage(z,Path.Combine(d,"stage"),r,"x86"); }); });
  Test("reject package architecture mismatch", delegate { string d=Dir(),z=Path.Combine(d,"a.zip"); Zip(z,"cc-switch.exe","portable.ini"); Reject(delegate { Core.ExtractPackage(z,Path.Combine(d,"stage"),R(),"arm64"); }); });
  Test("data prefers USERPROFILE database over legacy HOME", delegate { string h=Dir(),l=Dir(); Directory.CreateDirectory(Path.Combine(h,".cc-switch")); File.WriteAllText(Path.Combine(h,".cc-switch","cc-switch.db"),"data"); Assert(Core.ResolveDataDirectory(h,l,Path.Combine(h,"none"))==Path.Combine(h,".cc-switch"),"wrong home"); });
  Test("data falls back to legacy HOME database only when default absent", delegate { string h=Dir(),l=Dir(); Directory.CreateDirectory(Path.Combine(l,".cc-switch")); File.WriteAllText(Path.Combine(l,".cc-switch","cc-switch.db"),"legacy"); Assert(Core.ResolveDataDirectory(h,l,Path.Combine(h,"none"))==Path.Combine(l,".cc-switch"),"missing fallback"); });
  Test("existing store override wins", delegate { string h=Dir(),custom=Dir(),store=Path.Combine(h,"paths.json"); File.WriteAllText(store,"{\"app_config_dir_override\":\""+custom.Replace("\\","\\\\")+"\"}"); Assert(Core.ResolveDataDirectory(h,null,store)==custom,"override"); });
  Test("corrupt store fails closed rather than guessing backup location", delegate { string h=Dir(),store=Path.Combine(h,"paths.json"); File.WriteAllText(store,"broken"); Reject(delegate { Core.ResolveDataDirectory(h,null,store); }); });
  Test("atomic install preserves neighbors and backs up data and old executable", delegate { string d=Dir(),data=Dir(),backups=Dir(); string target=Target(d),stage=Path.Combine(Dir(),"new.exe"); File.WriteAllText(stage,"new"); File.WriteAllText(Path.Combine(data,"cc-switch.db"),"database"); File.WriteAllText(Path.Combine(data,"settings.json"),"settings"); string b=Core.Install(stage,d,data,backups); Assert(File.ReadAllText(target)=="new","not replaced"); Assert(File.ReadAllText(Path.Combine(d,"Reasonix.exe"))=="untouched","neighbor changed"); Assert(File.ReadAllText(Path.Combine(d,"portable.ini"))=="portable=true","marker changed"); Assert(File.ReadAllText(Path.Combine(b,"cc-switch.exe"))=="old","missing original"); Assert(File.ReadAllText(Path.Combine(b,"data","cc-switch.db"))=="database","missing data"); Assert(File.ReadAllText(Path.Combine(data,"settings.json"))=="settings","changed live settings"); Assert(new DirectoryInfo(b).GetAccessControl().AreAccessRulesProtected,"backup ACL is inherited"); });
  Test("locked executable leaves original unchanged", delegate { string d=Dir(), target=Target(d),stage=Path.Combine(Dir(),"new.exe"); File.WriteAllText(stage,"new"); bool rejected=false; using(var locked=new FileStream(target,FileMode.Open,FileAccess.Read,FileShare.None)) { try { Core.Install(stage,d,Dir(),Dir()); } catch(IOException) { rejected=true; } } Assert(rejected,"lock ignored"); Assert(File.ReadAllText(target)=="old","original damaged"); });
  Test("locked database aborts before replacing executable", delegate { string d=Dir(),target=Target(d),data=Dir(),db=Path.Combine(data,"cc-switch.db"),stage=Path.Combine(Dir(),"new.exe"); File.WriteAllText(stage,"new"); File.WriteAllText(db,"database"); bool rejected=false; using(var locked=new FileStream(db,FileMode.Open,FileAccess.Read,FileShare.None)) { try { Core.Install(stage,d,data,Dir()); } catch(IOException) { rejected=true; } } Assert(rejected,"db lock ignored"); Assert(File.ReadAllText(target)=="old","replaced despite backup failure"); });
  Test("backup inside data is rejected to prevent recursive copy", delegate { string d=Dir(),target=Target(d),data=Dir(),stage=Path.Combine(Dir(),"new.exe"); File.WriteAllText(stage,"new"); Reject(delegate { Core.Install(stage,d,data,Path.Combine(data,"backup")); }); Assert(File.ReadAllText(target)=="old","changed"); });
  Test("missing portable marker aborts install", delegate { string d=Dir(),target=Path.Combine(d,"cc-switch.exe"),stage=Path.Combine(Dir(),"new.exe"); File.WriteAllText(target,"old"); File.WriteAllText(stage,"new"); Reject(delegate { Core.Install(stage,d,Dir(),Dir()); }); Assert(File.ReadAllText(target)=="old","changed"); });
  Console.WriteLine("RESULT " + passed + " passed, " + failed + " failed. Fixtures retained: " + root);
  return failed==0?0:1;
 }
}
